repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff .
        language: system
        always_run: true
        pass_filenames: false
      - id: docs
        name: docs
        entry: python3 docs/abstractions.py
        language: system
        always_run: true
        pass_filenames: false
      - id: flake8
        name: flake8
        entry: flake8 --statistics -j4
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy tinygrad/ extra/helpers.py
        language: system
        always_run: true
        pass_filenames: false
      - id: tests
        name: subset of (CPU) tests
        entry: env CPU=1 pytest test/unit/ test/test_ops.py test/test_dtype.py test/test_schedule.py test/test_custom_function.py test/test_assign.py test/test_symbolic_shapetracker.py test/external/test_example.py
        language: system
        always_run: true
        pass_filenames: false
      - id: pylint
        name: pylint
        entry: python -m pylint tinygrad/
        language: system
        always_run: true
        pass_filenames: false
